#!/usr/bin/env python

#RUN - par128
#snakemake -p -s Snakefile --cores 128

#DAG
#snakemake -s Snakefile --dag | dot -Tsvg > dag.svg

configfile: "config.yaml"

import pandas as pd
import yaml
import itertools

lista_genotipos=["B1","B2","Co06022","Co8021","CoV92102","CP74-2005","F1-Bulk-1","F1-Bulk-2","FN95-1702","GN18","GT96-167","GUC10","GUC2","GXU-34140","GXU-34176","KQ08-2850","KQB07-23863","KQB07-23990","KQB07-24619","KQB07-24739","KQB08-32953","KQB09-20432","KQB09-20620","KQB09-23137","LCP85-384","MS6847","MT11-610","Q200","Q241","QA02-1009","QA96-1749","QBYN04-26041","QC02-402","QN05-1460","QN05-1509","QN05-1743","QN05-803","QS99-2014","RB72454","RB855156","ROC20","ROC22","ROC26","SP80-3280","T1","T2","TUC717","US851008"]

identity = config["identity"]

localrules: all, identity

rule all:
    input:
        expand("{genotype1}_{genotype2}.identity.08.txt", genotype1=lista_genotipos, genotype2=lista_genotipos)

rule concatenate:
    input:
        "../../results/{genotype1}_transcriptome.cpc_ncrnas.fa",
        "../../results/{genotype2}_transcriptome.cpc_ncrnas.fa"
    output:
        "{genotype1}_{genotype2}_temp.fa"
    threads: 2
    log:
        "identity_logs/{genotype1}_{genotype2}.concatenate.log"
    shell:
        """
	cat {input[0]} {input[1]} > {output[0]} 2>> {log[0]}
	"""

rule identity:
    input:
        "{genotype1}_{genotype2}_temp.fa"
    output:
        "{genotype1}_{genotype2}.identity.08.txt"
    threads: 2
    log:
        "identity_logs/{genotype1}_{genotype2}.identity.08.log"
    shell:
        """
        {identity} -d {input[0]} -o {output[0]} -t 0.8 -c {threads} 2>> {log[0]}
        rm {input[0]}
        """

