#!/usr/bin/env python

#RUN - serial
#snakemake -np -s Snakefile --cores 1 --jobs 16

#DAG
#snakemake -s Snakefile --dag | dot -Tsvg > dag.svg

configfile: "config.yaml"

import pandas as pd
import yaml

genotypes = pd.read_csv("genotypes.csv")

meshclust = config["meshclust"]

localrules: all, meshclust

rule all:
	input:
		expand("{genotype}.meshclust.09.txt", genotype=genotypes)
		
rule meshclust:
	input:
		expand("../../results/{{genotype}}_transcriptome.cpc_ncrnas.fa", genotype=genotypes)
	output:
		expand("{{genotype}}.meshclust.09.txt", genotype=genotypes)
	threads: 8
	log:
		expand("identity_logs/{{genotype}}.meshclust.09.log", genotype=genotypes)
	shell:
		"{meshclust} -d {input} -o {output} -t 0.9 -c {threads}"
