#!/usr/bin/env python

#RUN - par128
#snakemake -p -s Snakefile --cores 128

#DAG
#snakemake -s Snakefile --dag | dot -Tsvg > dag.svg

configfile: "config.yaml"

import pandas as pd
import yaml

lista_genotipos=["B1","B2","Co06022","Co8021","CoV92102","CP74-2005","F1-Bulk-1","F1-Bulk-2","FN95-1702","GN18","GT96-167","GUC10","GUC2","GXU-34140","GXU-34176","KQ08-2850","KQB07-23863","KQB07-23990","KQB07-24619","KQB07-24739","KQB08-32953","KQB09-20432","KQB09-20620","KQB09-23137","LCP85-384","MS6847","MT11-610","Q200","Q241","QA02-1009","QA96-1749","QBYN04-26041","QC02-402","QN05-1460","QN05-1509","QN05-1743","QN05-803","QS99-2014","RB72454","RB855156","ROC20","ROC22","ROC26","SP80-3280","T1","T2","TUC717","US851008"]

#lista_genotipos=["HB1"]

parts=[1,2,3,4,5,6,7,8,9,10]

txCdsPredict = config["txCdsPredict"]
feature_extraction = config["feature_extraction"]
weka_jar = config["weka_jar"]
RNAplonc_model = config["RNAplonc_model"]
FilterResults = config["FilterResults"]
extractRNAploncNonCodingSequences = config["extractRNAploncNonCodingSequences"]

rule all:
    input:
        expand("{genotype}_rnaplonc_ncrnas.fa", genotype=lista_genotipos, part=parts)

rule split_input:
    input:
        "../../3_noncodingSequences/results/{genotype}_transcriptome.cpc_ncrnas.fa"
    output:
        expand("../results/genotype_parts/{{genotype}}_transcriptome.cpc_ncrnas.part-{part}.fa", part=parts)
    threads: 1
    resources:
        load=1
    shell:
        """
        ./fasta-splitter.pl --n-parts 10 --out-dir ./../results/genotype_parts/ --line-length --nopad {input[0]}
        """

rule txCdsPredict:
    input:
        "../results/genotype_parts/{genotype}_transcriptome.cpc_ncrnas.part-{part}.fa"
    output:
        "../results/txCdsPredict/{genotype}_{part}_transcriptome_cd-hit08_cds.fasta"
    threads: 1
    resources:
        load=1
    shell:
        """
        {txCdsPredict} {input[0]} {output[0]}
        """

rule feature_extraction:
    input:
        "../results/genotype_parts/{genotype}_transcriptome.cpc_ncrnas.part-{part}.fa",
        "../results/txCdsPredict/{genotype}_{part}_transcriptome_cd-hit08_cds.fasta"
    output:
        "../results/feature_extraction/{genotype}_{part}_transcriptome_cd-hit08_cds.arff"
    threads: 1
    resources:
        load=1
    shell:
        """
        perl {feature_extraction} {input[0]} {input[1]} > {output[0]}
        """

rule RNAplonc:
    input:
        "../results/feature_extraction/{genotype}_{part}_transcriptome_cd-hit08_cds.arff"
    output:
        "../results/RNAplonc/{genotype}_{part}_transcriptome_rnaplonc.txt"
    threads: 1
    resources:
        load=1
    shell:
        """
        java -cp {weka_jar} weka.classifiers.trees.REPTree -l {RNAplonc_model} -T {input[0]} -p 0 > {output[0]}
        """

rule filter_result:
    input:
        "../results/txCdsPredict/{genotype}_{part}_transcriptome_cd-hit08_cds.fasta",
        "../results/RNAplonc/{genotype}_{part}_transcriptome_rnaplonc.txt"
    output:
        "../results/RNAplonc_lncRNAs_filtered/{genotype}_{part}_RNAplonc_lncRNAs.txt"
    threads: 1
    resources:
        load=1
    shell:
        """
        python3 {FilterResults} -c {input[0]} -r {input[1]} -o {output[0]} -p 0.5 -t 1
        """

rule concatenate_result:
    input:
        parts = expand("../results/RNAplonc_lncRNAs_filtered/{genotype}_{part}_RNAplonc_lncRNAs.txt", genotype=lista_genotipos, part=parts)
    output:
        final = "../results/RNAplonc_lncRNAs_filtered_final/{genotype}_RNAplonc_lncRNAs.txt",
        mod = "../results/RNAplonc_lncRNAs_filtered_final/{genotype}_RNAplonc_lncRNAs.mod.txt"
    threads: 1
    params:
        part_of_file=' '.join([f"../results/RNAplonc_lncRNAs_filtered/{{genotype}}_{part}_RNAplonc_lncRNAs.txt" for part in parts])
    resources:
        load=1
    shell:
        """
        cat {params.part_of_file} >> {output.final}
        awk '{{print $1}}' {output.final} >> {output.mod}
        """

rule extract_ncrnas:
    input:
        "../results/RNAplonc_lncRNAs_filtered_final/{genotype}_RNAplonc_lncRNAs.mod.txt",
        "../../3_noncodingSequences/results/{genotype}_transcriptome.cpc_ncrnas.fa"
    output:
        "{genotype}_rnaplonc_ncrnas.fa"
    threads: 1
    resources:
        load=1
    shell:
        """
        {extractRNAploncNonCodingSequences} -rnaplonc {input[0]} -transcriptome {input[1]}
        """
